### ISSUE TITLE
Issues trying to build and run the consuming solution 

### ISSUE THREAD

**Issue by haroon-oxts** [MicrosoftDocs/xamarin-docs#1764] opened 2019-06-04 14:16 UTC
First off thanks for the tutorial it really did got a long way demystifying the different steps involved to use C++ in Xamarin. I have followed the article closely but unfortunately I am stuck with some errors when trying to run the solution. Some additional information:

- I am working with VS for Mac
- I have verified that the simulators are using compatible processors (x84_64 for the android project and an iPhone 8 with 64 bit arm)

Android at runtime
```
System.DllNotFoundException: libMathFuncs.so
  at at (wrapper managed-to-native) MathFuncs.MyMathFuncsWrapper.CreateMyMathFuncs()
  at MathFuncs.MyMathFuncs..ctor () [0x00006] in /Users/hhaider/Projects/MathFuncs/MathFuncs.Shared/MyMathFuncs.cs:11
  at MathFuncsApp.MainPage.OnAppearing () [0x00008] in /Users/hhaider/Projects/MathFuncsApp/MathFuncsApp/MainPage.xaml.cs:19
  at Xamarin.Forms.Page.SendAppearing () [0x00024] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:359
  at Xamarin.Forms.Platform.Android.PageRenderer.OnAttachedToWindow () [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs:53
  at Android.Views.View.n_OnAttachedToWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in &lt;788a34f7a7b84486905dfde786529d42&gt;:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.33(intptr,intptr)
```
Log of the console output for Android
```
[Mono] DllImport attempting to load: 'libMathFuncs.so'.
[Mono] DllImport error loading library '/storage/emulated/0/Android/data/com.hhcorp.mathfuncsapp/files/.__override__/libMathFuncs.so': 'dlopen failed: library "/storage/emulated/0/Android/data/com.hhcorp.mathfuncsapp/files/.__override__/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/storage/emulated/0/Android/data/com.hhcorp.mathfuncsapp/files/.__override__/libMathFuncs.so': 'dlopen failed: library "/storage/emulated/0/Android/data/com.hhcorp.mathfuncsapp/files/.__override__/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/system/lib/libMathFuncs.so': 'dlopen failed: library "/system/lib/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/system/lib/libMathFuncs.so': 'dlopen failed: library "/system/lib/libMathFuncs.so" not found'.
[Mono] DllImport error loading library 'libMathFuncs.so': 'dlopen failed: library "libc++_shared.so" not found'.
[chatty] uid=10082(com.hhcorp.mathfuncsapp) identical 1 line
[Mono] DllImport error loading library 'libMathFuncs.so': 'dlopen failed: library "libc++_shared.so" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "libc++_shared.so" not found'.
[Mono] DllImport attempting to load: 'libMathFuncs.so'.
[Mono] DllImport error loading library '/storage/emulated/0/Android/data/com.hhcorp.mathfuncsapp/files/.__override__/libMathFuncs.so': 'dlopen failed: library "/storage/emulated/0/Android/data/com.hhcorp.mathfuncsapp/files/.__override__/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/storage/emulated/0/Android/data/com.hhcorp.mathfuncsapp/files/.__override__/libMathFuncs.so': 'dlopen failed: library "/storage/emulated/0/Android/data/com.hhcorp.mathfuncsapp/files/.__override__/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/system/lib/libMathFuncs.so': 'dlopen failed: library "/system/lib/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/system/lib/libMathFuncs.so': 'dlopen failed: library "/system/lib/libMathFuncs.so" not found'.
[Mono] DllImport error loading library 'libMathFuncs.so': 'dlopen failed: library "libc++_shared.so" not found'.
[chatty] uid=10082(com.hhcorp.mathfuncsapp) identical 1 line
[Mono] DllImport error loading library 'libMathFuncs.so': 'dlopen failed: library "libc++_shared.so" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "libc++_shared.so" not found'.
```

iOS at build time gets the following error:
```
 MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_main'.
    MTOUCH : error MT5213: Duplicate symbol in: /Users/hhaider/Projects/MathFuncsApp/MathFuncsApp.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone10.4-12.1/mtouch-cache/libMathFuncs.a(MyMathFuncsTest.o) (Location related to previous error)
    MTOUCH : error MT5213: Duplicate symbol in: /Users/hhaider/Projects/MathFuncsApp/MathFuncsApp.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone10.4-12.1/mtouch-cache/x86_64/main.o (Location related to previous error)
    error MT5209 : Native linking error : 1 duplicate symbol for architecture x86_64
    MTOUCH : error MT5202: Native linking failed. Please review the build log.
```
This appears to get fixed if I use the command "--registrar:static" in the iOS Build options in the iOS project head. I just found this from a google search and I don't know what really means, any help on this would be much appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Use C/C++ libraries with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/#feedback)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by mikeparker104** [comment] 2019-06-06 10:34
Thanks for reaching out and glad the tutorial was helpful to you. Are you able to build and run the complete code sample successfully without hitting the same errors?

**Comment by haroon-oxts** [comment] 2019-06-06 10:41
As of now I am still hitting the same errors as mentioned above, the iOS route can be solved with that "--registrar:static" option but I don't really appreciate why at the moment, could you shed some light on this if you have a moment?

As far as the Android version goes, I don't really have any ideas at the moment of how to troubleshoot it beyond confirming again that all the configuration options are the same as in the article. If you have a hunch about why the simulator was not able to load the .so file it would be amazing to hear it!

**Comment by conceptdev** [comment] 2019-06-21 16:36
This appears to be a [duplicate of the issue](https://github.com/xamarin/mobcat/issues/27) raised for the extended version of this article. The errors were related to creating the native libraries which is out of scope for this article. The build script has subsequently been updated to work with a newer version of the Android NDK and iOS SDK. The `--register:static` mtouch argument is used to explicitly select the [static registrar](https://docs.microsoft.com/xamarin/ios/internals/registrar#new-registration-system) which might have potentially stripped out the duplicate symbol in this case but should not have been necessary. The error no longer appears when using the precompiled sample version of the library, or a newly compiled version generated by the provided build script. There are a number of potential reasons why the [MT5212](https://docs.microsoft.com/xamarin/ios/troubleshooting/mtouch-errors#mt5212-native-linking-failed-duplicate-symbol-) and [MT5213](https://docs.microsoft.com/xamarin/ios/troubleshooting/mtouch-errors#mt5213-duplicate-symbol-in--location-related-to-previous-error) toolchain errors were encountered as described in the [mtouch errors documentation](https://docs.microsoft.com/xamarin/ios/troubleshooting/mtouch-errors#mt5xxx-gcc-and-toolchain-error-messages). Adding `-vvvv` to the additional mtouch build arguments to get a more verbose build log will aid in troubleshooting should these error be encountered in future.

**Closed by conceptdev** 2019-06-21 16:36 UTC
Labels: Cross-platform
