### ISSUE TITLE
Hyperlinks without end tags on the page

### ISSUE THREAD

**Issue by MFinkBK** [MicrosoftDocs/xamarin-docs#2902] opened 2020-06-04 08:58 UTC
It seems the page has some links that have no closing tags, e.g. in the heading "Building Universal Native Libraries (i386, ARMv7, and ARM64)" or "Accessing C Methods from C#", which makes reading the text a bit harder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6324b2-d690-3265-39e2-d5a57fcc1083
* Version Independent ID: b7553f1b-1ed1-27fb-5e11-b91f609d32b1
* Content: [Referencing Native Libraries in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/native-interop)
* Content Source: [docs/ios/platform/native-interop.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/native-interop.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment] 2020-06-09 10:46
Hi @MFinkBK 


Thanks for opening this issue. The issue was caused by an updated version of markdig that's used by the docs build system. It handles HTML that's embedded in markdown more strictly. I've updated all the affected pages, and so the issue is now fixed.

**Closed by davidbritch** 2020-06-09 10:46 UTC
Labels: iOS
