### ISSUE TITLE
big section of content is hyperlinked

### ISSUE THREAD

**Issue by Edgaras91** [MicrosoftDocs/xamarin-docs#2893] opened 2020-06-01 11:04 UTC
the whole "Using Custom Themes" section is "linked" to nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b678e7-5336-db4f-02ac-db6d2115ebec
* Version Independent ID: 5434c705-8fa7-f2ed-e358-6c05d915cde0
* Content: [Material Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/material-theme)
* Content Source: [docs/android/user-interface/material-theme.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/material-theme.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment] 2020-06-09 10:47
Hi @Edgaras91 

Thanks for opening this issue. The issue was caused by an updated version of markdig that's used by the docs build system. It handles HTML that's embedded in markdown more strictly. I've updated all the affected pages, and so the issue is now fixed.

**Closed by davidbritch** 2020-06-09 10:47 UTC
Labels: Android
