### ISSUE TITLE
The FastRing link does not work.

### ISSUE THREAD

**Issue by rieou** [MicrosoftDocs/xamarin-docs#309] opened 2018-05-23 03:02 UTC
The fastring link returns an application error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79320e9a-8b52-1c24-0a5b-a7ef6a32b519
* Version Independent ID: 88548723-6f1b-50c1-163c-a9e151b024e8
* Content: [Xamarin Live Player Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/install?tabs=ios%2Cwindows#feedback)
* Content Source: [docs/tools/live-player/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/install.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by asb3993** [comment] 2018-05-23 21:27
Duplicate of #307

**Closed by asb3993** 2018-05-23 21:27 UTC
Labels: duplicate
