### ISSUE TITLE
many section of this page had been treat as hyperlink

### ISSUE THREAD

**Issue by FatJohn** [MicrosoftDocs/xamarin-docs#2890] opened 2020-06-01 02:00 UTC
[Enter feedback here]
as title. And It makes reading experience not quiet good.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d2ced57-2bbb-5f7c-f7fa-ddef0553bf3d
* Version Independent ID: 1730ad55-9606-06e7-7c59-51cb04a30a0b
* Content: [Dialogs in Xamarin.Mac - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/user-interface/dialog)
* Content Source: [docs/mac/user-interface/dialog.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/user-interface/dialog.md)
* Product: **xamarin**
* Technology: **xamarin-mac**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment] 2020-06-09 10:48
Hi @FatJohn 

Thanks for opening this issue. The issue was caused by an updated version of markdig that's used by the docs build system. It handles HTML that's embedded in markdown more strictly. I've updated all the affected pages, and so the issue is now fixed.

**Closed by davidbritch** 2020-06-09 10:48 UTC
Labels: macOS
