### ISSUE TITLE
Entire sections rendered as hyperlinks

### ISSUE THREAD

**Issue by RaelsonCraftz** [MicrosoftDocs/xamarin-docs#2882] opened 2020-05-29 18:07 UTC
Seems like a quick fix. A few whole sections are being rendered as hyperlinks. They are:

https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons#adding-alternate-icons-to-a-xamarinios-project

https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons#managing-the-apps-icon

https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons#summary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c62db7d0-fe9a-c7a3-4c2a-f39bebd958fb
* Version Independent ID: fddd63c8-8ba9-0230-8145-771af251daf1
* Content: [Alternate App Icons in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons)
* Content Source: [docs/ios/app-fundamentals/images-icons/alternate-app-icons.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/images-icons/alternate-app-icons.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment] 2020-06-09 10:48
Hi @RaelsonCraftz 


Thanks for opening this issue. The issue was caused by an updated version of markdig that's used by the docs build system. It handles HTML that's embedded in markdown more strictly. I've updated all the affected pages, and so the issue is now fixed.

**Closed by davidbritch** 2020-06-09 10:48 UTC
Labels: iOS
