### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by wcoder** [MicrosoftDocs/xamarin-docs#2881] opened 2020-05-29 16:26 UTC
Look at section:

> 2. Instantiate a UISwipeActionsConfiguration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fefd2f5f-9794-9903-83b0-3b847005dd9e
* Version Independent ID: c7d3cc42-9051-f3a4-3793-9d5c291a4907
* Content: [Working with Row Actions in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/tables/row-action)
* Content Source: [docs/ios/user-interface/controls/tables/row-action.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/tables/row-action.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment] 2020-06-09 10:49
Hi @wcoder 

Thanks for opening this issue. The issue was caused by an updated version of markdig that's used by the docs build system. It handles HTML that's embedded in markdown more strictly. I've updated all the affected pages, and so the issue is now fixed.

**Closed by davidbritch** 2020-06-09 10:49 UTC
Labels: iOS
