### ISSUE TITLE
This installation is the start, but...

### ISSUE THREAD

**Issue by Darlanio** [MicrosoftDocs/xamarin-docs#1608] opened 2019-04-16 00:10 UTC
This installation is the start, but a lot more is required before you can open a template, compile, get the emulator started and see the result. The Xamarin has been a product for about 5 years now, but it still feels very immature due to the lacking a one button click that installs everything and makes computer ready for the first project to be compiled and debugged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc5d4b4-e0c4-7399-8e32-2c2fe935cbbe
* Version Independent ID: 89992fd0-d78a-fc6f-16f9-1ee91cf18485
* Content: [Installing Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/installation/?tabs=windows&pivots=windows#feedback)
* Content Source: [docs/get-started/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/installation/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JustinMinnaar** [comment] 2019-04-28 08:34
I agree. I'm suprised that after spending hours to install, that when creating a default app I have to wait for 10 minutes for a compile and receive a mix of errors about missing dependencies and downloads, and the need to run nuget to download missing files.

**Comment by conceptdev** [comment] 2019-05-01 18:25
@Darlanio thanks for the feedback. I'm closing this issue as a duplicate of your other issue https://github.com/MicrosoftDocs/xamarin-docs/issues/1609, since you provided a little more info there.

**Closed by conceptdev** 2019-05-01 18:25 UTC
Labels: Xamarin.Forms
