### ISSUE TITLE
Image is not appearing in the sample WorkingWithImages

### ISSUE THREAD

**Issue by JayramJai** [MicrosoftDocs/xamarin-docs#1979] opened 2019-07-31 07:13 UTC
setting the Embbed image and download image source is not appearing in the attached sample WorkingWithImages. Can you provide the solution for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows#feedback)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**
![image](https://user-images.githubusercontent.com/48436989/62191372-fd6dba00-b390-11e9-823a-96bbaa909160.png)
![image](https://user-images.githubusercontent.com/48436989/62191384-03fc3180-b391-11e9-8ca8-eff00d2a83a0.png)

**Comment by davidbritch** [comment] 2019-08-01 16:27
Hi @JayramJai 

I agree that the downloaded image isn't working, which I'll get fixed tomorrow. But the embedded image is working for me:

![Screenshot_1564676792](https://user-images.githubusercontent.com/8092460/62310478-911eb380-b481-11e9-9628-233a164af3b1.png)

**Comment by JayramJai** [comment] 2019-08-02 06:59
Thanks for the reply. I could see the build action of the beach.JPG in the pcl was None when it set to embbedResources it works. Let me know why the download image is not showing when you get to know.

**Comment by davidbritch** [comment] 2019-08-02 09:57
This is now fixed. The issue is that the downloadable image no longer exists online, so I've updated the URL to an image that does exist.

**Closed by davidbritch** 2019-08-02 09:57 UTC
Labels: Xamarin.Forms

**Comment by JayramJai** [comment] 2019-08-02 10:16
Thanks david
