### ISSUE TITLE
Setting the Label and App Icon

### ISSUE THREAD

**Issue by JNickVA1** [MicrosoftDocs/xamarin-docs#659] opened 2018-08-10 20:16 UTC
I have followed the Quickstart using the Visual Studio 2017, v15.8.0 Preview 5 as specified in the tutorial, and the steps listd for "Setting the Label and App Icon" cannot be followed since the Resources (the mipmaps) do not match what the text states and shows. Which, if any, of the .png files do I delete? For example, in the Preview version of VS 2017 with the Blank App project type selected, I have 3 png files listed under mipmap-hdpi and none of them are named "icon.png". I have shown in my mipmap-hdpi the following files: ic_launcher.png, ic_launcher_foreground.png, and ic_launcher_round.png. 

Please advise as to what I should actually do in this step (the "Setting the Label and App Icon" step above).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment] 2018-08-11 00:35
Hello @JNickVA1, thank you for your feedback! That topic is currently being updated to reflect the new templates that will be included in v15.8.0. Meanwhile, for help with using the preview, please visit the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Closed by mgmclemore** 2018-08-11 00:35 UTC

**Comment by jtepaa** [comment] 2018-09-17 04:53
I have followed the tutorial step by step but my "large text" "plain text" and "button" all overlap.

Please advise how to change so that they appear underneath each other as pictured in the tutorial.

**Comment by dalek09** [comment] 2019-01-21 16:20
For me, the overlapping items is caused by a missing + sign in the id of the android:layout_below i.e. when I drag a control I get e.g.
	<Button
		android:text="Translate"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@+id/PhoneNumberText"
		android:id="@+id/TranslateButton" />
	<TextView
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@+id/TranslateButton"
		android:id="@id/TranslatedPhoneword" 
		android:text="" />
If there's anything wrong with these constraints they are simply and silently ignored!
I blieve that this is a bug in VS2017 V15.9.5 (and possibly others)

**Comment by dalek09** [comment] 2019-01-21 16:24
Above should have had:-

**Comment by dalek09** [comment] 2019-01-21 16:24
Arghh! Can't put XML snippet in here!
