### ISSUE TITLE
page has headers and body text as one big hyperlink

### ISSUE THREAD

**Issue by jmegner** [MicrosoftDocs/xamarin-docs#2905] opened 2020-06-04 20:07 UTC
In sections "Background Thread Example" and "Async/Await example", the section headers and paragraph text are displayed as a hyperlink.

I think the problem is that the page has each of those section inside an anchor element.  Usually sections have an h2 element that contains an anchor element.  Seems like these two problematic sections got that kind of switched up.

Good section header on the page:
```
<h2 id="ui-thread-execution">
    UI Thread Execution
    <a class="docon docon-link heading-anchor" href="#ui-thread-execution" ...></a>
</h2>
```

First bad section:
```
<a name="Background_Thread_Example">
<h2 id="background-thread-example">Background Thread Example</h2>
<p> ... </p>
<p> ... </p>
...
</a>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce237171-03a8-e451-1396-392666317a1d
* Version Independent ID: f77537a3-fea5-706a-6df4-b9f608e210b5
* Content: [Working with the UI Thread in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/ios-ui/ui-thread)
* Content Source: [docs/ios/user-interface/ios-ui/ui-thread.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/ios-ui/ui-thread.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by jmegner** [comment] 2020-06-04 22:09
Same issue on [another page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/automation-properties#automationpropertiesisinaccessibletree).

**Comment by davidbritch** [comment] 2020-06-09 10:46
Hi @jmegner 

Thanks for opening this issue. The issue was caused by an updated version of markdig that's used by the docs build system. It handles HTML that's embedded in markdown more strictly. I've updated all the affected pages, and so the issue is now fixed.

**Closed by davidbritch** 2020-06-09 10:46 UTC
Labels: iOS
