### ISSUE TITLE
What mean awaited and awaits?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/xamarin-docs#1890] opened 2019-07-10 20:57 UTC
@wang-chi commented on [Wed Jul 10 2019](https://github.com/MicrosoftDocs/xamarin-docs.zh-tw/issues/23)

I think this problem due to translate cause.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 3e6b1679-7d43-32c2-0ea9-72c2bda2da06
* Version Independent ID: 63828f35-0a1e-1613-bc7f-4f8d95ac3fe7
* Content: [非同步支援概觀 - Xamarin](https://docs.microsoft.com/zh-tw/xamarin/cross-platform/platform/async)
* Content Source: [docs/cross-platform/platform/async.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-TW/blob/live/docs/cross-platform/platform/async.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by lichasu** [comment] 2019-07-10 21:09
Hi team,

The are a couple of instances of "`await`ed" and  "`await`s" in the document which breaks the way files the files are translated so they show up like this, making no sense in the target languages:

![image](https://user-images.githubusercontent.com/51962333/61004547-9b470980-a33c-11e9-8a97-9a1869ae25bc.png)

All text in the box (for example `await`) is not translatable, so it leaves a dangling "ed" or "s" that can't be translated. Those sentences should be rephrased so that they could be localized correctly.

Thanks!

CC: @JasonCard

**Comment by conceptdev** [comment] 2019-07-10 22:02
Agreed - we did not foresee this problem when the original content was written. Thank you for the feedback!

**Comment by JasonCard** [comment] 2019-07-10 22:43
@lichasu Thank you for reporting this issue.
@conceptdev Also agree that English source will need to be fixed in these cases, so translation will make sense.

**Comment by davidbritch** [comment] 2020-12-23 12:31
Thanks for submitting an issue and we apologize for the delayed response. The requested updates haven't been made since the creation of the issue, and the timeline for resolution may vary based on resourcing, so the issue is being moved to an internal repo to better track it.

**Closed** 2021-01-14 16:11 UTC
Labels: Cross-platform, Pri2, loc, xamarin-crossplatform/tech, xamarin/prod
