### ISSUE TITLE
Should be documented as "experimental"

### ISSUE THREAD

**Issue by ArgusMagnus** [MicrosoftDocs/xamarin-docs#1837] opened 2019-07-01 10:29 UTC
`Shell` and its related additions (`SearchHandler`s, etc.) should be clearly documented as `experimental` as they are (as of XF 4.0.0.540366) nowhere near release/production quality.

**Comment by davidbritch** [comment] 2019-07-05 09:10
Closed as a duplicate of #1838

**Closed by davidbritch** 2019-07-05 09:10 UTC
Labels: Xamarin.Forms
