### ISSUE TITLE
Xamarin Forms - Android 7+ support

### ISSUE THREAD

**Issue by rcunniffe** [MicrosoftDocs/xamarin-docs#909] opened 2018-10-16 10:46 UTC
Hey,

In reference to official documentation: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases

I have been using this plugin for some some, but the playstore now require an app to target android version 7 at a minimum. When i target this, the application cannot "Open the database" it only works for lower version of android.

I get a datapath for android like so Path.Combine(global::Android.OS.Environment.ExternalStorageDirectory.Path, filename);

Then when starting my app try to open the database connection like so

string dbPath = DependencyService.Get<IFileHelper>().GetLocalFilePath("myDbName.db3");
var conn = new SQLiteAsyncConnection(dbPath);            
The exception is:

Unhandled Exception:

SQLite.SQLiteException: Could not open database file: /storage/emulated/0/myDbName.db3 (CannotOpen)

I've also ensure i have read and write ticked for external storage permission. I've been stuck on this for sometime and not sure what to do?

**Comment by conceptdev** [comment] 2018-10-16 17:11
This seems to be a duplicate of https://github.com/MicrosoftDocs/xamarin-docs/issues/908 ?

Please verify you are using the correct NuGet package.

**Closed by conceptdev** 2018-10-16 17:11 UTC

**Comment by rcunniffe** [comment] 2018-10-17 09:03
@conceptdev replied on the other post. Yes i was but not actually looking for user's permission... which article does not really reference right?

**Comment by conceptdev** [comment] 2018-10-18 17:07
Interesting point about permissions. I think we wrote it with the expectation of using internal storage, but off-the-top-of-my-head I can't recall if that has different permissions characteristics. Something for us to look in to, and maybe add a note or something for others in your situation! Thanks for the follow-up.
