### ISSUE TITLE
Xamarin.Essentials Feature Guides - Liquid Error

### ISSUE THREAD

**Issue by jpriestley70** [MicrosoftDocs/xamarin-docs#2886] opened 2020-05-30 18:33 UTC
On the Feature Guides for Xamarin Essentials next to the date there is a Liquid error.
For example:
https://docs.microsoft.com/en-us/xamarin/essentials/clipboard?context=xamarin/xamarin-forms

**Xamarin.Essentials: Clipboard**
01/06/2020 Liquid error: parsing "{0}" - Quantifier {x,y} following nothing.

Feature guides I've also seen the error on:
- Accelerometer
- App Information
- Email
- File System Helper
- Flashlight

Not checked all the feature guide pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/?WT.mc_id=docs-dotnet-learn)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment] 2020-05-30 18:45
@davidbritch ?

**Comment by davidbritch** [comment] 2020-05-31 09:48
Interestingly, including this error only repos if the `context` query param is supplied to the URL e.g. the following repros the error:

https://docs.microsoft.com/en-us/xamarin/essentials/accelerometer?context=xamarin/android

The following doesn't repro the error:

https://docs.microsoft.com/en-us/xamarin/essentials/accelerometer

@jasoncard Could this be anything to do with the `no-loc` metadata I recently added? The `Liquid error` is only occurring on Xamarin.Essentials docs though - not on the Xamarin.Forms docs, which gained identical `no-loc` metadata.

**Comment by davidbritch** [comment] 2020-06-01 10:17
This is being investigated internally by the docs support team.

**Comment by JasonCard** [comment] 2020-06-01 23:00
@davidbritch I'm not sure if this was caused by the added `no-loc` metadata, but thank you for adding me and I would also like to know what the root cause and solution will be.

**Comment by JasonCard** [comment] 2020-06-03 19:09
It looks like the issue is fixed in live page, but didn't see any change in source.

**Comment by davidbritch** [comment] 2020-06-08 09:26
@JasonCard Someone from docs support fixed this, but didn't tell me what the problem was. Regardless, the problem was external to this repo.

**Closed by davidbritch** 2020-06-08 09:26 UTC
Labels: Essentials
