### ISSUE TITLE
Null check doesn't seem right

### ISSUE THREAD

**Issue by mjwills** [MicrosoftDocs/xamarin-docs#1727] opened 2019-05-27 01:26 UTC
public void CancelSpeech()
{
    if (cts?.IsCancellationRequested ?? false)
        return;

    cts.Cancel();
}

The above code will call `cts.Cancel` even if `cts` is `null` - which doesn't seem correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c941b98c-cfe4-a6c9-2117-f5f0d2f5a7f8
* Version Independent ID: 7fe2d995-09dd-2dce-2dbf-7f49e6d7c3f1
* Content: [Xamarin.Essentials: Text-to-Speech - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/text-to-speech#feedback)
* Content Source: [docs/essentials/text-to-speech.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/text-to-speech.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by viveknatarajan** [comment] 2019-05-29 17:27
@mjwills : Thank you for the suggestion. The issue is fixed.

**Comment by conceptdev** [comment] 2019-05-29 23:27
Fixed in linked PR

**Comment by mjwills** [comment] 2019-05-29 23:57
The original bug is fixed - thanks for that. But I think it still may be incorrect. Now it only cancels **if** `IsCancellationRequested` is already `true` (which seems odd).

I would imagine:

```if (cts?.IsCancellationRequested ?? true)
        return;

cts.Cancel();```

may perhaps be better?

**Comment by conceptdev** [comment] 2019-05-30 00:05
@jamesmontemagno do you have any thoughts?

**Comment by jamesmontemagno** [comment] 2019-05-30 00:18
So.... maybe we just do something like:

```csharp
if (cts == null || !cts.IsCancellationRequested)
        return;

cts.Cancel();
```

**Comment by mjwills** [comment] 2019-05-30 01:06
I suspect you may have meant:

```if (cts == null || cts.IsCancellationRequested)```

?

_I suspect you want to call `Cancel` **only if** cancellation has **not** already been requested._

**Comment by viveknatarajan** [comment] 2019-05-30 08:56
> 
> 
> So.... maybe we just do something like:
> 
> ```cs
> if (cts == null || !cts.IsCancellationRequested)
>         return;
> 
> cts.Cancel();
> ```

@jamesmontemagno Current code below also does the same.

`if (cts?.IsCancellationRequested ?? false)
        cts.Cancel();`

**Comment by viveknatarajan** [comment] 2019-05-30 08:58
> 
> 
> I suspect you may have meant:
> 
> `if (cts == null || cts.IsCancellationRequested)`
> 
> ?
> 
> _I suspect you want to call `Cancel` **only if** cancellation has **not** already been requested._

@mjwills : Correct me if i'm wrong, we will cancel a task only when user requested cancellation. Current code is doing it.

**Comment by mjwills** [comment] 2019-05-30 09:25
Perhaps I am confused, if so I do apologise. My understanding is that the way that `cts.IsCancellationRequested` gets set to `true` is by a call to `cts.Cancel()`. As such, what I **assume** (perhaps incorrectly) is the intent of this code is that you want to call `cts.Cancel()` if it **is not already cancelled**.

That is why:

```if (cts == null || !cts.IsCancellationRequested)
        return;

cts.Cancel();```

Seems odd to me. There are three scenarios. Let's go through them one by one.

a) `cts` is `null`.  We return. Makes sense.
b) `cts.IsCancellationRequested` is `true`. We call `Cancel()` again.
c) `cts.IsCancellationRequested` is `false`. We return.

It seems to me that b) and c) may be wrong.

b) isn't necessary - `IsCancellationRequested` is already `true` - we don't need to call `Cancel` again (it is **already** cancelled). The net effect is that we cancel something that is already cancelled.
And c), by returning seems odd too. The method is called `CancelSpeech` - but it only cancels the speech **if it is already cancelled**.

It seems to me (and again, apologies if I am misunderstanding) that b) and c) are the wrong way around.

My suggestion is thus to do something like:

```if (cts?.IsCancellationRequested ?? true)
        return;

cts.Cancel();```

Which leave a) as is, and inverts b) and c).

**Comment by viveknatarajan** [comment] 2019-05-30 10:27
> 
> 
> Perhaps I am confused, if so I do apologise. My understanding is that the way that `cts.IsCancellationRequested` gets set to `true` is by a call to `cts.Cancel()` (see https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.cancel?view=netframework-4.8#System_Threading_CancellationTokenSource_Cancel and https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.iscancellationrequested?view=netframework-4.8). As such, what I **assume** (perhaps incorrectly) is the intent of this code is that you want to call `cts.Cancel()` if it **is not already (previously) cancelled**.
> 
> That is why:
> 
> ```
> if (cts == null || !cts.IsCancellationRequested)
>         return;
> 
> cts.Cancel();
> ```
> 
> Seems odd to me. There are three scenarios. Let's go through them one by one.
> 
> a) `cts` is `null`. We return. Makes sense.
> b) `cts.IsCancellationRequested` is `true`. We call `Cancel()` again.
> c) `cts.IsCancellationRequested` is `false`. We return.
> 
> It seems to me that b) and c) may be wrong.
> 
> b) isn't necessary - `IsCancellationRequested` is already `true` - we don't need to call `Cancel` again (it is **already** cancelled). The net effect is that we cancel something that is already cancelled.
> And c), by returning seems odd too. The method is called `CancelSpeech` - but it only cancels the speech **if it is already cancelled**.
> 
> It seems to me (and again, apologies if I am misunderstanding) that b) and c) are the wrong way around.
> 
> My suggestion is thus to do something like:
> 
> ```
> if (cts?.IsCancellationRequested ?? true)
>         return;
> 
> cts.Cancel();
> ```
> 
> Which leave a) as is, and inverts b) and c).
> 
> _If what I am saying doesn't make sense - feel free to close this. Perhaps I am misunderstanding what you are suggesting._

@mjwills : My apologise, you are right here. When user wants to cancel, it is enough to check for null and call cancel. `SpeakAsync` function should listen to `IsCancellationRequested` and cancel the async operation.

So the below code would do the trick. 

`if (cts?.IsCancellationRequested ?? false)
        cts.Cancel();`

**Comment by mjwills** [comment] 2019-05-30 11:03
```if (cts != null) cts.Cancel();``` looks great, thanks!

**Comment by jamesmontemagno** [comment] 2019-05-30 23:31
The code I listed is correct to show you how to cancel it from your UI

```csharp
if (cts == null || !cts.IsCancellationRequested)
        return;

cts.Cancel();
```

* If null: you can't cancel so don't do anything
* If cancellation is already requested don't do anything
* else cancel.

This code is correct.

**Comment by mjwills** [comment] 2019-05-30 23:37
> Sorry, i need to look at this again...

Yep, that is consistent with my earlier suggestions.

**Comment by jamesmontemagno** [comment] 2019-05-30 23:39
I am testing the code i linked to as I suspect it is wrong

**Comment by jamesmontemagno** [comment] 2019-05-30 23:40
Here we go: https://github.com/MicrosoftDocs/xamarin-docs/pull/1747/files#diff-31d82219c1d664944a65152c430a1299

This is correct like your suggestion was ;)

**Comment by mjwills** [comment] 2019-05-31 07:47
I would suggest using the code I suggested instead.

On 30 May 2019 8:27 pm, VivekNatarajan <notifications@github.com> wrote:

Perhaps I am confused, if so I do apologise. My understanding is that the way that cts.IsCancellationRequested gets set to true is by a call to cts.Cancel() (see https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.cancel?view=netframework-4.8#System_Threading_CancellationTokenSource_Cancel and https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.iscancellationrequested?view=netframework-4.8). As such, what I assume (perhaps incorrectly) is the intent of this code is that you want to call cts.Cancel() if it is not already (previously) cancelled.

That is why:

if (cts == null || !cts.IsCancellationRequested)
        return;

cts.Cancel();


Seems odd to me. There are three scenarios. Let's go through them one by one.

a) cts is null. We return. Makes sense.
b) cts.IsCancellationRequested is true. We call Cancel() again.
c) cts.IsCancellationRequested is false. We return.

It seems to me that b) and c) may be wrong.

b) isn't necessary - IsCancellationRequested is already true - we don't need to call Cancel again (it is already cancelled). The net effect is that we cancel something that is already cancelled.
And c), by returning seems odd too. The method is called CancelSpeech - but it only cancels the speech if it is already cancelled.

It seems to me (and again, apologies if I am misunderstanding) that b) and c) are the wrong way around.

My suggestion is thus to do something like:

if (cts?.IsCancellationRequested ?? true)
        return;

cts.Cancel();


Which leave a) as is, and inverts b) and c).

If what I am saying doesn't make sense - feel free to close this. Perhaps I am misunderstanding what you are suggesting.

@mjwills<https://github.com/mjwills> : My apologise, you are right here. When user wants to cancel, it is enough to check for null and call cancel. SpeakAsync function should listen to IsCancellationRequested and cancel the async operation.

So the below code would do the trick.

if (cts?.IsCancellationRequested ?? false) cts.Cancel();

**Comment by jamesmontemagno** [comment] 2019-05-31 16:51
Yes, I am suggesting your code in my PR :)

**Comment by mjwills** [comment] 2019-06-01 07:33
Apologies, I replied to that email a long time ago (and before the prior message was edited in such a way as to make my response make no sense anyway) - I am not sure why it popped up so late. I'll remove it now.

**Closed** 2019-06-03 08:59 UTC
Labels: Essentials
