### ISSUE TITLE
Last part of the page is one big link

### ISSUE THREAD

**Issue by wegascee** [MicrosoftDocs/xamarin-docs#2897] opened 2020-06-03 08:59 UTC
I don't think the last part of the page should be one link. Perhaps you forgot a closing tag.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaddaa8d-6e8e-8b12-bcf4-284175238bbe
* Version Independent ID: 6e3d847c-badc-904d-0ff5-a66e1fc8bc81
* Content: [Inspector Installation and Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/inspector/install?tabs=windows)
* Content Source: [docs/tools/inspector/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/inspector/install.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment] 2020-06-09 10:47
Hi @wegascee 

Thanks for opening this issue. The issue was caused by an updated version of markdig that's used by the docs build system. It handles HTML that's embedded in markdown more strictly. I've updated all the affected pages, and so the issue is now fixed.

**Closed by davidbritch** 2020-06-09 10:47 UTC
Labels: Tools
