### ISSUE TITLE
Visual Studio Xamarin IOS - Pair to Mac Error - OPENSSH IS Not Supported

### ISSUE THREAD

**Issue by liliyashka** [MicrosoftDocs/xamarin-docs#993] opened 2018-11-06 02:54 UTC
I get an error when trying to connect to my mac. I can connect with putty and I can ping my mac ip address but I can not pair with visual studio. Visual studio connected and even installed missing mono files but when it trys to further connect I get this error. I spent about 10 hours on this one issue. I reinstalled OSX. Im running OSX Mojave clean booted. I cleaned caches, restarted pc and mac. Created new ip address and so on and nothing works. I breaks right after it says starting connection to ........ Then the error shows up -> (Key OPENSSH is not supported)

So I can see that the connection works and I can input login info each time no problem. But while trying to connect I get this OPENSSH is not supported error. 

Here is a video to the problem:
https://www.youtube.com/watch?v=KTobenSKUm8&t=1s

Here are some error reports:
configuration for connecting to '192.168.213.130' 
Checking SSH configuration... 
Checking available disk space... 
Checking Mono installation... 
Checking Xamarin iOS installation... 
Checking host configuration for connecting to '192.168.213.130'... 
Host '192.168.213.130' is configured correctly Starting connection to '192.168.213.130'... 
Starting connection to '192.168.213.130'... 
Starting disconnection from 192.168.213.130... 
Starting disconnection from 192.168.213.130... 
The connection to '192.168.213.130' has been finished Couldn't connect to 192.168.213.130. 
Please try again

Please can anyone help with this issue it has been going on for days now and I can not get any ios development done with this current error. Thank. you.

**Comment by conceptdev** [comment] 2018-11-06 19:03
this is a duplicate of [this issue](https://github.com/MicrosoftDocs/xamarin-docs/issues/979#issuecomment-435472203). please follow the instructions there to file a bug.

**Closed by conceptdev** 2018-11-06 19:03 UTC
