### ISSUE TITLE
Typo for conditional logical AND operator

### ISSUE THREAD

**Issue by wcoder** [MicrosoftDocs/xamarin-docs#1721] opened 2019-05-25 12:58 UTC
Typo for conditional logical AND operator in AwakeFromNib method of DesignerAwareLabel class

Shown `&amp;&amp;` instead of `&&`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7901b8-c995-7ca7-a0ff-0505ceac4115
* Version Independent ID: 5feed282-65ea-ca9c-a2b4-eb304d644a03
* Content: [Custom Controls in the Xamarin Designer for iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/designer/ios-designable-controls-overview#feedback)
* Content Source: [docs/ios/user-interface/designer/ios-designable-controls-overview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/designer/ios-designable-controls-overview.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by viveknatarajan** [comment] 2019-05-29 17:28
@wcoder : Thanks for the suggestion. The issue is fixed now.

**Closed** 2019-05-29 20:00 UTC
Labels: iOS
