### ISSUE TITLE
Is the minimum API 21 or 19?

### ISSUE THREAD

**Issue by jfichtner** [MicrosoftDocs/xamarin-docs#2209] opened 2019-10-08 14:09 UTC
The "Target Platforms" section says that the minimum OS is 5.0 (API 21), but the "Android" section says: "...the minimum version can be set to API 19 so you can continue to support devices that use Android 4.4 and newer". I have used the latest version of Xamarin.Forms to target a device running 4.4, and it works. Why does the Target Platforms section call out version 5.0 as the minimum?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443cf095-5281-a757-0005-60dd1c82899c
* Version Independent ID: fd91ca24-84ae-04e4-14b5-d6738f8c6527
* Content: [Xamarin.Forms Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/requirements?tabs=windows)
* Content Source: [docs/get-started/requirements.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/requirements.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment] 2019-10-09 09:45
Hi @jfichtner 

I'm going to close this issue because it's a duplicate of https://github.com/MicrosoftDocs/xamarin-docs/issues/1969

However, I'm going to follow up on the issue there.

**Closed by davidbritch** 2019-10-09 09:45 UTC
Labels: Xamarin.Forms
