### ISSUE TITLE
Link Issue

### ISSUE THREAD

**Issue by Jayson-Furr** [MicrosoftDocs/xamarin-docs#2901] opened 2020-06-04 04:53 UTC
A lot of the page is one hyperlink.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb05328a-0bd2-189e-49e0-c38946b90a2e
* Version Independent ID: 9176ac5d-bfb0-72cc-b1c7-1da6c55c2d4f
* Content: [Creating and drawing on SkiaSharp bitmaps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/drawing)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/drawing.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/drawing.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment] 2020-06-09 10:47
Hi @Jayson-Furr 

Thanks for opening this issue. The issue was caused by an updated version of markdig that's used by the docs build system. It handles HTML that's embedded in markdown more strictly. I've updated all the affected pages, and so the issue is now fixed.

**Closed by davidbritch** 2020-06-09 10:47 UTC
Labels: graphics-games
